### ISSUE TITLE
PCI Compliance

### ISSUE THREAD

**Issue by vagelim** [ivanweiler/Inchoo_Stripe#8]
Use of this module is in [violation of PCI compliance](https://www.pcicomplianceguide.org/pci-faqs-2/) [standards](https://www.pcisecuritystandards.org/pdfs/pci_fs_data_storage.pdf) and can result in fines.

**Comment by ivanweiler** [comment]
Care to explain why in detail? Links you posted are giving the impression that module is saving cc data which is NOT true. Processing is done through api (as in most Magento gateway implementations at the time when this was coded), in a contrast to stripe.js implementation which would require javascript modifications on checkout and really difficult multicheckout implementation, all beyond scope of this free open source extension.

**Comment by vagelim** [comment]
> I wanted to share a warning with everyone about this extension. In case you think this extension will greatly alleviate your PCI-DSS burden, think again. This extension actually seems to work great (I like it for it's simplicity!), but this extension works very similar to other credit card gateway extensions, in that the credit card and security code are sent from the client's browser to your server, and then is transmitted from your server over to Stripe. Now there is absolutely nothing wrong with this, nothing at all. But since the cc details are being transmitted through your servers you are exposed to more stringent PCI-DSS requirements. I just wanted to clear that up since if you go to the Stripe website all they talk about is how awesome their javascript-based approach is, and how if you use the javascript api the credit card info never hits the merchant's server. Hope that helps someone.

http://reviews.magentocommerce.com/4643-en_us/10548/inchoo-inchoo-stripe-reviews/reviews.htm#BVRRDisplayContentReviewID_14645861

**Comment by ivanweiler** [comment]
Thanks for explanation, this is true. This implementation doesn't take PCI-DSS burden off, in contrast to stripe.js implementation. Since extension isn't actively maintained any more to start with, I added warning to main README suggesting people to use alternative Magento Connect extensions.

Regards, Ivan
